scoreName: "Test Score"
rndStrategy:
  pageRanges:
    - range: { start: 1, end: 8 }
      isRndActive: false
      instruments: [ all ]
    - range: { start: 9, end: 16 }
      isRndActive: true
      selectionRange: [ { start: 1, end: 8 } ]
      instruments: [ all ]
    - range: { start: 17, end: 24 }
      isRndActive: false
      instruments: [ all ]
    - range: { start: 25, end: 32 }
      isRndActive: true
      selectionRange: [ { start: 17, end: 24 } ]
      instruments: [ all ]
    - range: { start: 33, end: 40 }
      isRndActive: false
      instruments: [ all ]
    - range: { start: 41, end: 48 }
      isRndActive: true
      selectionRange: [ { start: 1, end: 8 },{ start: 17, end: 24 },{ start: 41, end: 48 } ]
      instruments: [ all ]
    - range: { start: 49, end: 52 }
      isRndActive: false
      instruments: [ all ]
    - range: { start: 53, end: 56 }
      isRndActive: true
      selectionRange: [ { start: 1, end: 8 } ]
      instruments: [ all ]
