scoreName: "Dialogs"
presets:
  - id: -2
    config:
      - granulator: {
        masterGainVal: 0.5,
        playDurationSec: 30.0,
        playStartOffsetSec: 0.0,
        maxGrains: 12,
        bufferPositionPlayRate: 0.2,
        audioStopToleranceMs: 5,
        isUsePositionOscillator: true,
        isUseSizeOscillator: true,
        isUsePositionFrequencyMod: true,
        isUsePositionRangeMod: true,
        panner: { isUsePanner: false, panningModel: "equalpower", distanceModel: "linear", maxPanAngle: 45 },
        envelope: { attackTime: 0.5, decayTime: 0.0, sustainTime: 0.0, releaseTime: 0.5, sustainLevel: 1.0 },
        grain: { sizeMs: 100, pitchRate: 0.3, maxPositionOffsetRangeMs: 100, maxPitchRateRange: 0.1, timeOffsetStepMs: 50 },
        positionOscillator: { minValue: 1000.0, maxValue: 7000.0, type: "TRIANGLE", frequency: 0.2,
                              frequencyLFO: { minValue: -0.19, maxValue: 0.5, type: "TRIANGLE", frequency: 0.05 },
                              startLFO: { minValue: -500.0, maxValue: 500.0, type: "TRIANGLE", frequency: 0.1 },
                              endLFO: { minValue: -1000.0, maxValue: 500.0, type: "TRIANGLE", frequency: 0.1 } },
        sizeOscillator: { minValue: -50.0, maxValue: 2000.0, type: "TRIANGLE", frequency: 0.5 },
      }
      - speechSynth: {
        volume: 1.0,
        pitch: 1.0,
        rate: 0.7,
        lang: "en-GB",
        maxVoiceLoadAttempts: 10,
        maxUtterances: 5,
        utteranceTimeoutSec: 30,
        isInterrupt: false,
        interruptTimeout: 250,
      }
  - id: -1
    scripts: [
        "webScore.setInstructions('','','', false);"
    ]
  - id: 0
    scripts: [
        "webScore.setInstructions('Get ready','Turn up the volume!','');"
    ]
  - id: 1
    scripts: [
        "webScore.resetState();",
        "webScore.setInstructions('Preparing for the next','<span style=\\'color:blueviolet;\\'>Dialog</span>', '');"
    ]
  - id: 2
    scripts: [
        "webScore.reset(1);",
        "webScore.reset(1002);",
        "webScore.setSection('pitch');",
        "webScore.activateViews('meter');",
        "webScore.deactivateViews('notes','audio','thumbs','vote');",
    ]
  - id: 3
    scripts: [
        "webScore.reset(1);",
        "webScore.reset(1003);",
        "webScore.setSection('rhythm');",
        "webScore.activateViews('meter');",
        "webScore.deactivateViews('notes','audio','thumbs','vote');",
    ]
  - id: 4
    scripts: [
        "webScore.reset(1);",
        "webScore.reset(1004);",
        "webScore.setSection('melody');",
        "webScore.activateViews('meter');",
        "webScore.deactivateViews('notes','audio','thumbs','vote');",
    ]
  - id: 5
    scripts: [
        "webScore.reset(1);",
        "webScore.reset(1005);",
        "webScore.setSection('timbre');",
        "webScore.activateViews('meter');",
        "webScore.deactivateViews('notes','audio','thumbs','vote');",
    ]
  - id: 1002
    config:
      - player: {
      audioFiles: [
          "/audio/DialogsPitch1-1.mp3",
          "/audio/DialogsPitch1-2.mp3",
          "/audio/DialogsPitch1-3.mp3",
          "/audio/DialogsPitch2-1.mp3",
          "/audio/DialogsPitch2-2.mp3",
          "/audio/DialogsPitch2-3.mp3",
          "/audio/DialogsPitch3-1.mp3",
          "/audio/DialogsPitch3-2.mp3",
          "/audio/DialogsPitch3-3.mp3"
      ],
      audioFilesIndexMap:  [
        [],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
      ],
    }
    scripts: [
    ]
  - id: 1003
    config:
      - player: {
      audioFiles: [
          "/audio/DialogsRhythm2-1.wav",
          "/audio/DialogsRhythm2-2.wav",
          "/audio/DialogsRhythm3-1.wav",
          "/audio/DialogsRhythm3-2.wav",
          "/audio/DialogsRhythm4-1.wav",
          "/audio/DialogsRhythm4-2.wav",
          "/audio/DialogsRhythm5-1.wav",
          "/audio/DialogsRhythm5-2.wav",
          "/audio/DialogsRhythm6-1.wav",
          "/audio/DialogsRhythm6-2.wav",
          "/audio/DialogsRhythm7-1.wav",
          "/audio/DialogsRhythm7-2.wav",
          "/audio/DialogsRhythm8-1.wav",
          "/audio/DialogsRhythm8-2.wav",
          "/audio/DialogsRhythm9-1.wav",
          "/audio/DialogsRhythm9-2.wav",
          "/audio/DialogsRhythm10-1.wav",
          "/audio/DialogsRhythm10-2.wav",
          "/audio/DialogsRhythm11-1.wav",
          "/audio/DialogsRhythm11-2.wav",
      ],
      audioFilesIndexMap:  [
        [],
        [0,1],
        [2,3],
        [4,5],
        [6,7],
        [8,9],
        [10,11],
        [12,13],
        [14,15],
        [16,17],
        [18,19],
      ],
    }
  - id: 1004
    config:
      - player: {
      audioFiles: [
          "/audio/DialogsMelody2-1.wav",
          "/audio/DialogsMelody2-2.wav",
          "/audio/DialogsMelody3-1.wav",
          "/audio/DialogsMelody3-2.wav",
          "/audio/DialogsMelody4-1.wav",
          "/audio/DialogsMelody4-2.wav",
          "/audio/DialogsMelody5-1.wav",
          "/audio/DialogsMelody5-2.wav",
          "/audio/DialogsMelody6-1.wav",
          "/audio/DialogsMelody6-2.wav",
          "/audio/DialogsMelody7-1.wav",
          "/audio/DialogsMelody7-2.wav",
          "/audio/DialogsMelody9-1.wav",
          "/audio/DialogsMelody9-2.wav",
          "/audio/DialogsMelody11-1.wav",
          "/audio/DialogsMelody11-2.wav",
          "/audio/DialogsMelody12-1.wav",
          "/audio/DialogsMelody12-2.wav",
      ],
      audioFilesIndexMap:  [
        [],
        [0,1],
        [2,3],
        [4,5],
        [6,7],
        [8,9],
        [10,11],
        [],
        [12,13],
        [],
        [14,15],
        [16,17],
      ],
    }
  - id: 1005
    config:
      - player: {
      audioFiles: [
          "/audio/DialogsTimbre2-1.wav",
          "/audio/DialogsTimbre2-2.wav",
          "/audio/DialogsTimbre3-1.wav",
          "/audio/DialogsTimbre3-2.wav",
          "/audio/DialogsTimbre4-1.wav",
          "/audio/DialogsTimbre4-2.wav",
          "/audio/DialogsTimbre5-1.wav",
          "/audio/DialogsTimbre5-2.wav",
          "/audio/DialogsTimbre6-1.wav",
          "/audio/DialogsTimbre6-2.wav",
          "/audio/DialogsTimbre7-1.wav",
          "/audio/DialogsTimbre7-2.wav",
          "/audio/DialogsTimbre9-1.wav",
          "/audio/DialogsTimbre9-2.wav",
          "/audio/DialogsTimbre10-1.wav",
          "/audio/DialogsTimbre10-2.wav",
          "/audio/DialogsTimbre11-1.wav",
          "/audio/DialogsTimbre12-1.wav",
          "/audio/DialogsTimbre12-2.wav",
      ],
      audioFilesIndexMap:  [
        [],
        [ 0,1 ],
        [ 2,3 ],
        [ 4,5 ],
        [ 6,7 ],
        [ 8,9 ],
        [ 10,11 ],
        [ 6,7 ],
        [ 12,13 ],
        [ 14,15 ],
        [ 16,1 ],
        [ 17,18 ],
      ],
    }