scoreName: "Dialogs"
rndStrategy:
  isActive: false
  pageRanges:
    - range: { start: 1, end: 5 }
      isRndActive: false
      instruments: [ all ]
builderStrategy:
  isActive: true
  sections: [pitch, rhythm]
  assignmentType: USER_ANY_FCFS
  isStopOnSectionEnd: true
  pageRanges:
    - range: { start: 1, end: 5 }
      name: pitch
      instruments: [ all ]
    - range: { start: 1, end: 5 }
      name: rhythm
      instruments: [ all ]
transpositionStrategy:
  isActive: true
  topStaveYRef: 114
  topStaveXRef: 80
  botStaveYRef: 335
  botStaveXRef: 80
  minYdistance: 10
  minXdistance: 7
  pages:
    - {pageNo: 1, part: Present, textElements: [{ dx: 0, dy: 113, txt: C }, { dx: 0, dy: 123, txt: G }]}
    - {pageNo: 2, part: Present, textElements: [{ dx: 0, dy: 113, txt: C }, { dx: 0, dy: 123, txt: G }]}