scoreName: "Symphonea"
presets:
  - id: -2
    config:
      - granulator: {
        masterGainVal: 0.5,
        playDurationSec: 30.0,
        playStartOffsetSec: 0.0,
        maxGrains: 12,
        bufferPositionPlayRate: 0.2,
        audioStopToleranceMs: 5,
        isUsePositionOscillator: true,
        isUseSizeOscillator: true,
        isUsePositionFrequencyMod: true,
        isUsePositionRangeMod: true,
        panner: { isUsePanner: false, panningModel: "equalpower", distanceModel: "linear", maxPanAngle: 45 },
        envelope: { attackTime: 0.5, decayTime: 0.0, sustainTime: 0.0, releaseTime: 0.5, sustainLevel: 1.0 },
        grain: { sizeMs: 100, pitchRate: 0.3, maxPositionOffsetRangeMs: 100, maxPitchRateRange: 0.1, timeOffsetStepMs: 50 },
        positionOscillator: { minValue: 1000.0, maxValue: 7000.0, type: "TRIANGLE", frequency: 0.2,
                              frequencyLFO: { minValue: -0.19, maxValue: 0.5, type: "TRIANGLE", frequency: 0.05 },
                              startLFO: { minValue: -500.0, maxValue: 500.0, type: "TRIANGLE", frequency: 0.1 },
                              endLFO: { minValue: -1000.0, maxValue: 500.0, type: "TRIANGLE", frequency: 0.1 } },
        sizeOscillator: { minValue: -50.0, maxValue: 2000.0, type: "TRIANGLE", frequency: 0.5 },
      }
      - speechSynth: {
        volume: 1.0,
        pitch: 1.0,
        rate: 0.7,
        lang: "en-GB",
        maxVoiceLoadAttempts: 10,
        maxUtterances: 5,
        utteranceTimeoutSec: 30,
        isInterrupt: false,
        interruptTimeout: 250,
      }
  - id: -1
    scripts: [
        "webScore.setInstructions('','','', false);"
    ]
  - id: 0
    scripts: [
        "webScore.setInstructions('Get ready','Turn up the volume!','');"
    ]
  - id: 1
    scripts: [
        "webScore.resetState();",
        "webScore.setInstructions('Preparing for the','<span style=\\'color:blueviolet;\\'>Symphonea</span>', 'performance');"
    ]
  - id: 2
    scripts: [
        "webScore.reset(1);",
        "webScore.reset(1002);",
    ]
  - id: 1002
    config:
      - player: {
        audioFiles: [
            "/audio/SymphoneaM1-1.wav",
        ],
        audioFilesIndexMap:  [
          [],
        ],
      }